url: http://lianluoyi.7766.org:30097
out_path: d:/我的/
tester: hwr
version: V4.1.0
max_workers: 10
head:
  Accept: application/json, text/plain, */*
  Cookie: jenkins-timestamper-offset=-28800000; JSESSIONID=b14a6843-56e6-4adc-a214-937c9b69fdab